# Author -- meevs
# Creation Date -- 2023-06-24
# File Name -- compose.yaml
# Notes --

version: "2.4"
services:
  default:
    build:
      context: "./"
      args:
        INSTALL_DIR: "${INSTALL_DIR}"
        CONFIG_PKG: "${CONFIG_PKG}"
    image: "bt-${SERVER_NAME}-img"
    container_name: "bt-${SERVER_NAME}"
    stdin_open: true
    tty: true
    ports:
     - "27015-27016:27015-27016/udp"
    volumes:
      - type: "volume"
        source: "data"
        target: "${INSTALL_DIR}"

volumes:
  data: {}
